### ISSUE TITLE
Inaccurate links in the left sidebar

### ISSUE THREAD

**Issue by franpog859** [Kong/kuma-website#46]
Hey! When I go to the [Kuma documentation](https://kuma.io/docs/0.1.2/#what-is-kuma) and click on for example the `CLI` link in the left sidebar, site scrolls down but not to the CLI section. At least not every time. 

To reproduce this bug go to the site and click on the links a few times. Try also the incognito window. I use Chrome `Version 76.0.3809.132 (Official Build) (64-bit)` and macOS `Mojave Version 10.14.5`

**Comment by bloqhead** [comment]
Hey there! Thanks for reporting this one. It's kind of a strange issue issue. [This PR](https://github.com/Kong/kuma-website/pull/36) provides a detailed explanation as to why this occurs and I've attempted a fix within the PR, but it could use some more testing. Can you test here and let me know if you still encounter the bug?

https://deploy-preview-36--kuma.netlify.com/

Thank you!

**Comment by franpog859** [comment]
I tried to reproduce the bug using your PR deployment. I was using Chrome `Version 77.0.3865.90 (Official Build) (64-bit)` and Windows `10 Home 10.0.18362 Build 18362` this time. I wasn't able to see it! It seems to be fixed. Tomorrow I'll try it on Mac

**Comment by bloqhead** [comment]
That's awesome! Thanks for testing and getting back to me!
